config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :user
  has_many :ingredients
  has_many :directions
  has_many :utensils


  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true

  accepts_nested_attributes_for :directions,
                                reject_if: proc { |attributes| attributes['step'].blank? },
                                allow_destroy: true

  accepts_nested_attributes_for :utensils,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true

  validates :title, :description, :image, presence: true
  has_attached_file :image, styles: { :medium => "400x400#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/models/utensil.rb
class Utensil < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipe = Recipe.all.order("created_at DESC")
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Created new recipe successfully!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe!"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy], utensils_attributes: [:id, :name, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Recipe Book</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :cocoon %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "Recipe Book", root_path %>
        </div>

        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "New Recipe", new_recipe_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Log In", new_user_session_path %>
            </li>
          </ul>
        <% end %>

      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert" %>
      <% end %>

    <%= yield %>
        </div>
  </body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline.clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: "form-input form-control" } %>
    <%= link_to_remove_association "Remove Step", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="errors">
      <p>
        <%= @recipe.errors.count %>
        Prevented this recipe froms saving
      </p>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>

      <div class="row">
        <div class="col-md-4">
          <h3>Ingredients</h3>
          <div id="ingredients">
            <%= f.simple_fields_for :ingredients do |ingredient| %>
              <%= render "ingredients_fields", f: ingredient %>
              <div class="links">
                <%= link_to_add_association "Add Ingredient", f, :ingredients %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-md-4">
          <h3>Directions</h3>
          <div id="directions">
            <%= f.simple_fields_for :directions do |direction| %>
              <%= render "directions_fields", f: direction %>
              <div class="links">
                <%= link_to_add_association "Add Step", f, :directions, class: "btn btn-default add-button" %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-md-4">
          <h3>Utensils</h3>
          <div id="utensils">
            <%= f.simple_fields_for :utensils do |utensil| %>
              <%= render "utensils_fields", f: utensil %>
              <div class="links">
                <%= link_to_add_association "Add Utensil", f, :utensils, class: "btn btn-default add-button" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>


  <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/_ingredients_fields.html.erb
<div class="form-inline.clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: "form-input form-control" } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_utensils_fields.html.erb
<div class="form-inline.clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: "form-input form-control" } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-sm-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium) %>
            <% end %>
          </div>
          <h2>
            <%= link_to recipe.title, recipe %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1>
          <%= @recipe.title %>
        </h1>
        <p class="description">
          <%= @recipe.description %>
        </p>
        <p>
          Submitted by
          <%= @recipe.user.email %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div id="utensils">
        <h2>Utensils</h2>
        <ul>
          <% @recipe.utensils.each do |utensil| %>
            <li>
              <%= utensil.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
        <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>